import type { Metadata } from 'next';
import './globals.css';
import Nav, { NavButton } from './nav/Nav';
import { Inter } from 'next/font/google';
import { NotificationProvider } from '@/components/notifications/NotificationContext';
import NotificationDisplay from '@/components/notifications/NotificationDisplay';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <NotificationProvider>
          <Nav>
            <NavButton href='/' text='Flashcard App'></NavButton>
            <NavButton href='/new' text='New'></NavButton>
          </Nav>
          {children}
          <NotificationDisplay />
        </NotificationProvider>
      </body>
    </html>
  );
}
