import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav, { NavButton } from './nav/Nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Nav>
          <NavButton href='#' text='Flashcard App'></NavButton>
          <NavButton href='#' text='New'></NavButton>
        </Nav>
        {children}
      </body>
    </html>
  );
}
